# Generated by Django 4.2.2 on 2023-06-24 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("evaluation", "0005_alter_response_reviewer"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResponseInsights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response_length", models.IntegerField()),
                (
                    "evaluation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluation.evaluation",
                    ),
                ),
                (
                    "participant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluation.participant",
                    ),
                ),
                (
                    "response",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluation.response",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionInsights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_responses", models.IntegerField()),
                ("response_rate", models.FloatField()),
                ("average_score", models.FloatField()),
                ("median_score", models.FloatField()),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluation.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParticipantInsights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_evaluations", models.IntegerField()),
                ("average_response_rate", models.FloatField()),
                ("average_score", models.FloatField()),
                ("median_score", models.FloatField()),
                (
                    "participant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluation.participant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvaluationInsights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_participants", models.IntegerField()),
                ("total_questions", models.IntegerField()),
                ("total_responses", models.IntegerField()),
                ("average_score", models.FloatField()),
                ("minimum_score", models.FloatField()),
                ("maximum_score", models.FloatField()),
                (
                    "evaluation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluation.evaluation",
                    ),
                ),
            ],
        ),
    ]
