# Generated by Django 4.2.2 on 2023-07-01 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evaluationinsights",
            name="total_participants",
        ),
        migrations.RemoveField(
            model_name="evaluationinsights",
            name="total_questions",
        ),
        migrations.RemoveField(
            model_name="evaluationinsights",
            name="total_responses",
        ),
    ]
